import type { WordPair } from "./game-reducer";

export const WORD_PAIRS: readonly WordPair[] = [
  {
    id: "food-apple-orange",
    category: "Food",
    civilian: "Apple",
    imposter: "Orange",
  },
  { id: "food-coffee-tea", category: "Food", civilian: "Coffee", imposter: "Tea" },
  { id: "food-pizza-burger", category: "Food", civilian: "Pizza", imposter: "Burger" },
  { id: "food-lemon-lime", category: "Food", civilian: "Lemon", imposter: "Lime" },
  { id: "food-pancake-waffle", category: "Food", civilian: "Pancake", imposter: "Waffle" },
  { id: "animals-lion-tiger", category: "Animals", civilian: "Lion", imposter: "Tiger" },
  { id: "animals-dolphin-whale", category: "Animals", civilian: "Dolphin", imposter: "Whale" },
  { id: "animals-frog-toad", category: "Animals", civilian: "Frog", imposter: "Toad" },
  { id: "animals-eagle-hawk", category: "Animals", civilian: "Eagle", imposter: "Hawk" },
  { id: "animals-rabbit-hamster", category: "Animals", civilian: "Rabbit", imposter: "Hamster" },
  { id: "objects-lamp-flashlight", category: "Objects", civilian: "Lamp", imposter: "Flashlight" },
  { id: "objects-pencil-pen", category: "Objects", civilian: "Pencil", imposter: "Pen" },
  { id: "objects-backpack-suitcase", category: "Objects", civilian: "Backpack", imposter: "Suitcase" },
  { id: "objects-mirror-window", category: "Objects", civilian: "Mirror", imposter: "Window" },
  { id: "objects-clock-watch", category: "Objects", civilian: "Clock", imposter: "Watch" },
  { id: "places-hotel-hospital", category: "Places", civilian: "Hotel", imposter: "Hospital" },
  { id: "places-library-bookstore", category: "Places", civilian: "Library", imposter: "Bookstore" },
  { id: "places-beach-pool", category: "Places", civilian: "Beach", imposter: "Pool" },
  { id: "places-airport-station", category: "Places", civilian: "Airport", imposter: "Train station" },
  { id: "places-museum-gallery", category: "Places", civilian: "Museum", imposter: "Gallery" },
  { id: "entertainment-movie-series", category: "Entertainment", civilian: "Movie", imposter: "TV series" },
  { id: "entertainment-concert-festival", category: "Entertainment", civilian: "Concert", imposter: "Festival" },
  { id: "entertainment-actor-director", category: "Entertainment", civilian: "Actor", imposter: "Director" },
  { id: "entertainment-comedy-drama", category: "Entertainment", civilian: "Comedy", imposter: "Drama" },
  { id: "entertainment-podcast-radio", category: "Entertainment", civilian: "Podcast", imposter: "Radio" },
  { id: "sports-tennis-badminton", category: "Sports", civilian: "Tennis", imposter: "Badminton" },
  { id: "sports-soccer-rugby", category: "Sports", civilian: "Soccer", imposter: "Rugby" },
  { id: "sports-skiing-snowboarding", category: "Sports", civilian: "Skiing", imposter: "Snowboarding" },
  { id: "sports-boxing-wrestling", category: "Sports", civilian: "Boxing", imposter: "Wrestling" },
  { id: "sports-surfing-sailing", category: "Sports", civilian: "Surfing", imposter: "Sailing" },
  { id: "jobs-chef-baker", category: "Jobs", civilian: "Chef", imposter: "Baker" },
  { id: "jobs-teacher-coach", category: "Jobs", civilian: "Teacher", imposter: "Coach" },
  { id: "jobs-pilot-captain", category: "Jobs", civilian: "Pilot", imposter: "Captain" },
  { id: "jobs-doctor-nurse", category: "Jobs", civilian: "Doctor", imposter: "Nurse" },
  { id: "jobs-photographer-reporter", category: "Jobs", civilian: "Photographer", imposter: "Reporter" },
  { id: "nature-river-waterfall", category: "Nature", civilian: "River", imposter: "Waterfall" },
  { id: "nature-forest-jungle", category: "Nature", civilian: "Forest", imposter: "Jungle" },
  { id: "nature-thunder-lightning", category: "Nature", civilian: "Thunder", imposter: "Lightning" },
  { id: "nature-island-peninsula", category: "Nature", civilian: "Island", imposter: "Peninsula" },
  { id: "nature-sunrise-sunset", category: "Nature", civilian: "Sunrise", imposter: "Sunset" },
];
